### ISSUE TITLE
"ERR: Content-Type not provided" when proxying RTSP stream with "!" symbol in password

### ISSUE THREAD

**Issue by tomskikh** [aler9/rtsp-simple-server#100]
## Which version are you using?

v0.10.0

## Which operating system are you using?

Ubuntu 18.04.5 LTS (Bionic Beaver)

## Describe the problem

In proxy mode, server cannot connect to the camera. Server prints
```
[path proxyStream] rtsp source ERR: Content-Type not provided
```

Camera: `XIANG MAI SMT-AFK2500`

<details>
  <summary>RTSP Simple Server logs</summary>

```
2020/10/09 10:53:15 [0/0/0] rtsp-simple-server v0.10.0
2020/10/09 10:53:15 [0/0/0] [TCP server] opened on :8554
2020/10/09 10:53:17 [1/0/0] [client 127.0.0.1:56448] connected
2020/10/09 10:53:17 [1/0/0] [client 127.0.0.1:56448] OPTIONS
2020/10/09 10:53:17 [1/0/0] [client 127.0.0.1:56448] DESCRIBE
2020/10/09 10:53:17 [1/0/0] [path proxyStream] starting on demand rtsp source
2020/10/09 10:53:17 [1/0/0] [path proxyStream] rtsp source started
2020/10/09 10:53:17 [1/0/0] [path proxyStream] connecting to rtsp source
2020/10/09 10:53:17 [1/0/0] [path proxyStream] rtsp source ERR: Content-Type not provided
2020/10/09 10:53:22 [2/0/0] [client 127.0.0.1:56542] connected
2020/10/09 10:53:22 [1/0/0] [client 127.0.0.1:56542] disconnected
2020/10/09 10:53:22 [2/0/0] [client 127.0.0.1:56544] connected
2020/10/09 10:53:22 [1/0/0] [client 127.0.0.1:56544] disconnected
2020/10/09 10:53:22 [1/0/0] [path proxyStream] connecting to rtsp source
2020/10/09 10:53:22 [1/0/0] [path proxyStream] rtsp source ERR: Content-Type not provided
```

</details>

<details>
  <summary>rtsp-simple-server.yml</summary>

```yaml
protocols: [ tcp ]
rtspPort: 8554
rtpPort: 8000
rtcpPort: 8001

readTimeout: 10s
writeTimeout: 5s

authMethods: [ basic, digest ]

runOnConnect:

metrics: no
pprof: no
logDestinations: [ stdout ]
logFile: rtsp-simple-server.log

paths:
  proxyStream:
    sourceProtocol: tcp
    sourceOnDemand: yes

    runOnInit:
    runOnDemand:
    runOnPublish:
    runOnRead:

    publishUser:
    publishPass:
    publishIps: [ ]

    readUser:
    readPass:
    readIps: [ ]
    source: "rtsp://192.168.1.99/user=tmp&password=BagRep1!&channel=1&stream=0.sdp"

```

</details>

VLC plays the stream fine when connected directly to the camera. I see the difference in `DESCRIBE` request:

<details>
  <summary>DESCRIBE request from the server</summary>
  
```
DESCRIBE rtsp://192.168.1.99:554/user=tmp&password=BagRep1%21&channel=1&stream=0.sdp RTSP/1.0
Accept: application/sdp
CSeq: 2
```

Response:
```
RTSP/1.0 200 OK
Server: H264DVR 1.0
Cseq: 2
```

</details>

<details>
  <summary>DESCRIBE request from VLC</summary>
  
```
DESCRIBE rtsp://192.168.1.99:554/user=tmp&password=BagRep1!&channel=1&stream=0.sdp RTSP/1.0
CSeq: 3
User-Agent: LibVLC/3.0.8 (LIVE555 Streaming Media v2018.02.18)
Accept: application/sdp
```

Response:
```
RTSP/1.0 200 OK
Content-Type: application/sdp
Server: H264DVR 1.0
Cseq: 3
Content-Base: rtsp://192.168.1.99:554/user=tmp&password=BagRep1!&channel=1&stream=0.sdp
Cache-Control: private
x-Accept-Retransmit: our-retransmit
x-Accept-Dynamic-Rate: 1
Content-Length: 429

v=0
o=- 38990265062388 38990265062388 IN IP4 192.168.1.99
s=RTSP Session
c=IN IP4 192.168.1.99
t=0 0
a=control:*
a=range:npt=0-
m=video 0 RTP/AVP 98
a=rtpmap:98 H265/90000 
a=range:npt=0-
a=framerate:0S
a=fmtp:98 profile-id=010101;sprop-pps=RAHA8vA8kA==;sprop-sps=QgEBAWAAAAMAsAAAAwAAAwB7oAPAgBDlja5JMvTcBAQEAg==;sprop-vps=QAEMAf//AWAAAAMAsAAAAwAAAwB7rAk=;sprop-sei=TgHlBF70AACA;
a=framerate:25
a=control:trackID=3
```

</details>

Maybe the issue in query parameters encoding (`password=BagRep1!` encoded to `password=BagRep1%21`).

**UPD**: the server proxies the stream fine if a password doesn't contain `!` symbol.

## Did you attach a network dump?

Yes.

## Attachments

Dump of the data between the server and the camera: [rtsp_simple_server.pcap.zip](https://github.com/aler9/rtsp-simple-server/files/5352438/rtsp_simple_server.pcap.zip)
Dump of the data between VLC and the camera (when connecting to the camera directly): [vlc.pcap.zip](https://github.com/aler9/rtsp-simple-server/files/5352440/vlc.pcap.zip). Just for comparison.
