### ISSUE TITLE
hope support out hls(m3u8)

### ISSUE THREAD

**Issue by seamanm** [aler9/rtsp-simple-server#102]
## Which version are you using?

v0.10

## Which operating system are you using?

Linux

## Enhancement request

hope support out hls(m3u8)

media server --->rtsp-simple-server,this server can out hls

**Comment by aler9** [comment]
Hi, this can be done with the help of some additional software:

1. Install `ffmpeg`

2. Start `rtsp-simple-server` with this configuration
```yaml
paths:
  hls:
    runOnPublish: ffmpeg -re -i rtsp://localhost:8554/$RTSP_SERVER_PATH -c copy -f hls -hls_time 1 -hls_list_size 3 -hls_flags delete_segments -hls_allow_cache 0 hls/stream.m3u8
```

3. Serve the `hls/` folder with an HTTP server.

Unfortunately i can't directly integrate these functionalities into the server, since HLS supports only H264 and AAC, while rtsp-simple-server must support also H265, Opus and a lot of codecs which are not compatible with HLS. That's the main difference between this server and the others.
