### ISSUE TITLE
fallback stream when no live source present

### ISSUE THREAD

**Issue by wwortel** [aler9/rtsp-simple-server#104]
## Which version are you using?

v0.10.1

## Which operating system are you using?

Linux (Debian)

## Enhancement request

Description
Would like to replace an Icecast application by rtsp-simple-server to reduce latency in the streaming of a live audio stream.
It is important to have the smallest delay possible between the live event and what people hear.
The live stream is only sent to the server during a limited time. Outside that time window one should hear an announcement message. In Icecast this is called a fallback stream. Can this behaviour be produced by rtsp-simple-server as it is now, and if so how, and if not, can this be added? Thank you.

**Comment by aler9** [comment]
Hello, this can't be done in the current version but can be implemented in a future ones by using redirects.
My idea is to add a parameter `fallback` to set a fallback url:
```yml
paths:
  mypath:
    fallback: rtsp://anotherserver/anotherurl
```

Of course there must be a client that is publishing the fallback stream - using files directly is not supported at the moment, since it would require implementing file parsers, increasing the size of the software and obtaining something that would surely be less versatile than common players like ffmpeg and gstreamer.

**Comment by aler9** [comment]
Fallback parameter is now fully supported in master and will be added to the next release.

**Comment by wwortel** [comment]
Thank you! Will give it a try. The announcement stream is just a mp3 file that is local on the server and I presume I can just make it available as a stream on localhost using ffmpeg.

**Comment by aler9** [comment]
> I presume I can just make it available as a stream on localhost using ffmpeg.

yes, exactly, use another path to publish the fallback stream:
```yml
paths:
  main:
    fallback: rtsp://localhost:8554/fallbackpath

  fallbackpath:
    runOnInit: ffmpeg -re -stream_loop -1 -i myfile.mp3 -c copy -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnInitRestart: yes
```
