### ISSUE TITLE
RTSP PROXY ISSUE

### ISSUE THREAD

**Issue by Tabarane** [aler9/rtsp-simple-server#1105]
## Which version are you using?

v0.20.0

## Which operating system are you using?

- [X] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [X] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I have camera which is sending some type of additional data and its cause the issue, idea is if im using FFMPEG to play it , it will give the below error

`[rtsp @ 000001c44d179e80] Nonmatching transport in server reply
rtsp://admin:admin1234@172.17.172.145:22101/1_88_1: Invalid data found when processing input`

then i try to use Proxy with the help of RTSP server and it give me the error attached in server debug log

Config.yml

FFMPEG option

```
van:
   runOnDemand: ffmpeg -thread_queue_size 512 -i rtsp://admin:admin1234@172.17.172.145:22101/1_88_1 -vcodec libx264 -preset veryfast -r 24 -g 2 -s 1280x720 -b:v 3000k -max_muxing_queue_size 4096 -f rtsp rtsp://127.0.0.1:$RTSP_PORT/$RTSP_PATH
   runOnDemandRestart: yes
   sourceAnyPortEnable: yes
```

Proxy option

```
  Vanp:
   source: rtsp://admin:admin1234@172.17.172.145:22101/1_88_1
   sourceOnDemand: yes
```
## Describe how to replicate the issue

1. start server
2. update config.yml
3. request rtsp feed
4. error appear

## Did you attach the server logs?

yes / no

YES
[server.log](https://github.com/aler9/rtsp-simple-server/files/9381264/server.log)

## Did you attach a network dump?

yes / no
NO

**Comment by aler9** [comment]
Hello, please provide a network dump, that can be generated in this way:
1) Download wireshark (https://www.wireshark.org/)
2) Start capturing on the interface used for exchanging RTSP (if the server and the target software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card)
3) Start the server and replicate the issue
4) Stop capturing, save the result in .pcap format
5) Attach

PS: when generating the network dump, use this configuration:

```yml
  Vanp:
   source: rtsp://admin:admin1234@172.17.172.145:22101/1_88_1
   sourceOnDemand: no
```

Start the server, wait 30seconds, stop the server, stop recording the dump and attach the dump.
