### ISSUE TITLE
Feature request: add API endpoint for generating VLM config for mosaic view

### ISSUE THREAD

**Issue by CodingSpiderFox** [aler9/rtsp-simple-server#1129]
## Describe the feature

I have multiple cameras that I manage using rtsp-simple-server.
I want to observe all camera streams at once with VLC Media player

There are some tutorials on how to generate VLM config files for displaying the streams all at once, for example this one: https://stackoverflow.com/questions/59180160/mosaic-of-rtsp-streams-vlc-3-0-8

I would like rtsp-simple-server to have an API endpoint that can provide a config file with all currently active streams provided by configuration lines like these

```
paths:
  cam:
    runOnInit: ffmpeg -f v4l2 -i /dev/video0 -pix_fmt yuv420p -preset ultrafast -b:v 600k -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnInitRestart: yes
 cam2:
    runOnInit: ffmpeg -f v4l2 -i /dev/video1 -pix_fmt yuv420p -preset ultrafast -b:v 600k -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnInitRestart: yes

```

The provided example from stackoverflow relies on a static, pregenerated background image, maybe there is also an option to let VLC draw the background dynamically to allow for easy change of the total pixel size of the picture(s) without having to recreate the background.
