### ISSUE TITLE
rpiCamera source: encoder_encode(): ioctl() failed

### ISSUE THREAD

**Issue by giano574** [aler9/rtsp-simple-server#1133]
## Which version are you using?

v0.20.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [x] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

After a while, `encoder_encode(): ioctl() failed` will appear, and the stream will stop working. `rtsp-simple-server` is still running, but the stream will never recover. Restarting `rtsp-simple-server` makes the stream work again until the next `ioctl() failed`.

## Describe how to replicate the issue

I don't think it is relevant that I am using HLS, but this is the configuration that I have used.
1. Start with default config. Enable HLS and disable other protocols.
2. Add the following path to the configuration file.
```
stream:
    source: rpiCamera
    rpiCameraWidth: 1920
    rpiCameraHeight: 1080
    rpiCameraFPS: 30
    rpiCameraIDRPeriod: 10
    rpiCameraProfile: main
    rpiCameraLevel: '4.1'
    rpiCameraBitrate: 8000000
``` 
3. Play the stream in a browser at `http://<ip>:8888/stream`.

## Did you attach the server logs?

no

## Did you attach a network dump?

no
