### ISSUE TITLE
Native Raspi Camera support doesn't work

### ISSUE THREAD

**Issue by olokos** [aler9/rtsp-simple-server#1161]
## Which version are you using?

v0.20.0

## Which operating system are you using?
Debian 11 Bullseye 32Bit on RPi 4B 4GB

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [x] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
Native Raspi Camera RTSP should work, but it doesn't, VLC never connects, despite the camera hardware being "used"
Description
![image](https://user-images.githubusercontent.com/1755581/191405872-bdd1dab4-9c11-4950-9a22-bf158fc08805.png)
Above is the result and attempt to connect, it just results in further spam.

## Describe how to replicate the issue

1. Use Pi 4B HQ Camera / IMX477
2. Use the config of:
```
paths:
  cam:
    source: rpiCamera
    rpiCameraCamID: 0
    rpiCameraWidth: 1344
    rpiCameraHeight: 992
    rpiCameraFPS: 100
    rpiCameraIDRPeriod: 60
    rpiCameraBitrate: 1000000
    rpiCameraProfile: main
    rpiCameraLevel: '4.2'
```
3. Start server

## Did you attach the server logs?

[yes](https://pastebin.com/PU5XQxkz)
