### ISSUE TITLE
Native Raspi Camera support doesn't work - most likely due to wrong mode being set

### ISSUE THREAD

**Issue by olokos** [aler9/rtsp-simple-server#1162]
## Which version are you using?

v0.20.0

## Which operating system are you using?
Debian 11 Bullseye 32Bit on RPi 4B 4GB

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [x] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
Native Raspi Camera RTSP should work, but it doesn't, VLC never connects, despite the camera hardware being "used"
Description
![image](https://user-images.githubusercontent.com/1755581/191405872-bdd1dab4-9c11-4950-9a22-bf158fc08805.png)
Above is the result and attempt to connect, it just results in further spam.

```
olokos@pi:~ $ libcamera-vid --list-camera
Available cameras
-----------------
0 : imx477 [4056x3040] (/base/soc/i2c0mux/i2c@1/imx477@1a)
    Modes: 'SRGGB10_CSI2P' : 1332x990 [120.05 fps - (696, 528)/2664x1980 crop]
           'SRGGB12_CSI2P' : 2028x1080 [50.03 fps - (0, 440)/4056x2160 crop]
                             2028x1520 [40.01 fps - (0, 0)/4056x3040 crop]
                             4056x3040 [10.00 fps - (0, 0)/4056x3040 crop]
```
Above are HQ Camera/IMX477 available resolutions and framerates.
Since 1332x990 gets converted to 1344x992 by VLC or ffmpeg, then I set this as my width and height.

I suspect the reason is that the wrong resolution is selected for this framerate.
It usually can be specified with `--mode 1332:990:10` but there's no such parameter available with latest release of rtsp-simple-server.
## Describe how to replicate the issue

1. Use Pi 4B HQ Camera / IMX477
2. Use the config of:
```
paths:
  cam:
    source: rpiCamera
    rpiCameraCamID: 0
    rpiCameraWidth: 1344
    rpiCameraHeight: 992
    rpiCameraFPS: 100
    rpiCameraIDRPeriod: 60
    rpiCameraBitrate: 1000000
    rpiCameraProfile: main
    rpiCameraLevel: '4.2'
```
3. Start server

## Did you attach the server logs?

[yes](https://pastebin.com/PU5XQxkz)

## Did you attach a network dump?

no, as it's internal issue, not network related.
