### ISSUE TITLE
no one is publishing to path 'cam'

### ISSUE THREAD

**Issue by AntouanK** [aler9/rtsp-simple-server#117]
Hi there.

Trying to serve rtsp for a couple of usb cameras I have.
I'm starting the docker container with my device, and when a client ( motioneye ) connects, I get this log
```
connected
OPTIONS
DESCRIBE
ERR: no one is publishing to path 'cam'
disconnected
```

my config
```
/rtsp-server >>> cat rtsp-simple-server.yml                                                                               [130]
                                                                                                                                 
paths:                                                                                                                           
  cam:                                                                                                                           
    runOnInit: vlc  -f v4l2 -i /dev/video0 -f rtsp --rtsp-tcp rtsp://localhost:$RTSP_PORT/$RTSP_PATH                             
    runOnInitRestart: yes   
```

also tried with
```
ffmpeg -f v4l2 -i /dev/video0 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
```

my command
```
docker run -d --name rtsp-server --device=/dev/video0 -v $(pwd)/rtsp-simple-server.yml:/rtsp-simple-server.yml -e RTSP_PROTOCOLS=tcp -p 8554:8554 aler9/rtsp-simple-server
```

any idea why I cannot see the camera video?
do I have to publish it somehow?

thank you

**Comment by aler9** [comment]
Hello,
This configuration works perfectly on my pc:
```yml
paths:                                                                                                                           
  cam:                                                                                                                           
    runOnInit: ffmpeg -f v4l2 -i /dev/video0 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnInitRestart: yes
```

Try it with a normal release (not with docker).

Afterwards, when you succeeded in making the camera works, you can try docker.
The docker image doesn't include ffmpeg (otherwise it would be huge), you must create a custom image with both rtsp-simple-server and ffmpeg inside, like this
```sh
docker build -t myimage - << EOF
FROM aler9/rtsp-simple-server AS server
FROM alpine:3.12
RUN apk add --no-cache ffmpeg
COPY --from=server /rtsp-simple-server /rtsp-simple-server
ENTRYPOINT [ "/rtsp-simple-server" ]
EOF
```

then
```
docker run --rm -it --network=host \
--device=/dev/video0 \
-e RTSP_PATHS_CAM_RUNONINIT='ffmpeg -f v4l2 -i /dev/video0 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH' \
myimage
```

(and it works)
