### ISSUE TITLE
A way to get a snapshot of the current stream? (usage with Home Assistant)

### ISSUE THREAD

**Issue by rszemplinski** [aler9/rtsp-simple-server#119]
## Which version are you using?

v0.12.0

## Which operating system are you using?

Linux

## Question

Was just wondering if there was a simple way to get a snapshot of the stream so that I could hook it up to homeassistant? Right now homeassistant requires an endpoint that retrieves a snapshot but I don't know if/how to do so using this server.

**Comment by jazzy348** [comment]
Hi,

Do you mean like a thumbnail? you can set FFMPEG to run every X time with something like this:

ffmpeg -y -i "rtmp://127.0.0.1/key" -ss 00:00:001 -vframes 1 -vf scale=-2:300 "thumbnail.png" then just use Express or something to host the PNG file. Not a neat solution I know but it would do the trick for now.

-Jazzy

**Comment by aler9** [comment]
Hello, i've read the [Home Assistant guide](https://www.home-assistant.io/integrations/generic/) and it indeed require a "still image url" to add a RTSP camera. I don't understand why they chose to do this, i would have improved Home Assistant to generate the pics by itself instead of requiring this. Anyway, here's how to generate the needed data by using rtsp-simple-server:

1. use Linux

2. Download rtsp-simple-server

3. install ffmpeg and nginx

4. Edit the server configuration, insert runOnPublish and runOnPublishRestart under the stream you're interested into:
    ```yml
    paths:
      stream:
        runOnPublish: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -vframes 1 -y thumbnail.jpg
        runOnPublishRestart: yes
    ```
   Start rtsp-simple-server. Now a pic called `thumbnail.jpg` will be generated every 5 seconds if a client is publishing to the path `/stream`.

5. Edit the nginx configuration, that is usually `/etc/nginx/sites-enabled/default`; find the `root` directive and insert the folder in which you've downloaded rtsp-simple-server (and thumbnail.jpg is generated)
    ```
    root /var/www/html;
    ```

6. restart nginx (sudo systemctl restart nginx). Now the snapshot will be available in 
    ```
    http://localhost/thumbnail.jpg
    ```
    and you can use this url in Home Assistant's `still_image_url`

**Comment by rszemplinski** [comment]
Thank you for this! Super detailed and gets the job done.

**Comment by davidhantson** [comment]
Hi @aler9 , I've tried your solution with an Eufy cam and Home Assistant running your docker on a QNap Container Station. So far so good, but .. the thumbnail is nowhere to be found, nor do I get any debugging information from the ffmpeg command. 

```yaml
room:
    source: rtsp://192.168.2.32:554/live0
    runOnInit: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -vframes 1 -y multimedia/thumbnail.jpg
    runOnInitRestart: yes
```

Using runOnPublish resulted in an error and crash in my case.
Any idea what I'm doing wrong? I shared the /multimedia folder with a host folder on the QNap.
