### ISSUE TITLE
webhooks and recording

### ISSUE THREAD

**Issue by dottgonzo** [aler9/rtsp-simple-server#122]
hi,
after several years using rtmp services, i'm trying this rtsp server and i'm looking for some functionality that seems missed:

1) will be supported "natively" some kind of recording process to store recording paths?
2) there is some kind of functionality that allows to notificate another server when a stream is start or reconect, like a webhook (maybe with a delayed  timeout)?

**Comment by aler9** [comment]
Hello,

> will be supported "natively" some kind of recording process to store recording paths

At the moment the recording is not native (since this would require supporting containers and codecs, but maybe one day we'll get to this point), but nothing forbids from using ffmpeg together with rtsp-simple-server to achieve the result:

```yml
paths:
  mystream:
    runOnPublish: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f mpegts $(date +'%s').ts 
    runOnPublishRestart: yes
```

This configuration saves all the streams published to path `mystream` as TS files.

> there is some kind of functionality that allows to notificate another server when a stream is start or reconect, like a webhook (maybe with a delayed timeout)?

Yes:

```yml
paths:
  mystream:
    runOnPublish: ./on_publish.sh
```

create a file named `on_publish.sh` with the following content
```
#!/bin/sh
trap 'curl http://webhook-on-disconnect' INT
curl http://webhook-on-connect
sleep 86400
```

if you don't care about the disconnect webhook, you can simply do:


```yml
paths:
  mystream:
    runOnPublish: http://webhook-on-connect
```
