### ISSUE TITLE
externalAuthenticationURL requested without POST data

### ISSUE THREAD

**Issue by j-schraeder** [aler9/rtsp-simple-server#1240]
First of all, thanks for this great project. Really helpful!

I think I found a bug in the external Authentication.
I am using the latest docker version of rtsp-simple-server (using version 0.20.2)

My config looks like this:

```
externalAuthenticationURL: http://10.20.20.75/testauth

paths:
  proxied1:
    # url of the source stream, in the format rtsp://user:pass@host:port/path
    source: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4
    sourceOnDemand: yes

  proxied2:
    source: rtsp://rtsp.stream/pattern
    sourceOnDemand: yes
````

The testauth endpoint is a simple nodejs express server.
When opening one of the streams using HLS with Chrome, the server will call the auth api endpoint, but the POST request will be empty.

Can you confirm this behaviour? Or am I missing something?
