### ISSUE TITLE
externalAuthenticationURL set and called, but POST body is empty

### ISSUE THREAD

**Issue by j-schraeder** [aler9/rtsp-simple-server#1241]
## Which version are you using?

v0.20.2

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

First of all, thanks for this great project. Really helpful!

I think I found a bug in the external Authentication.
I am using the latest docker version of rtsp-simple-server (using version 0.20.2)

My config looks like this:

```
externalAuthenticationURL: http://10.20.20.75/testauth

paths:
  proxied1:
    # url of the source stream, in the format rtsp://user:pass@host:port/path
    source: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4
    sourceOnDemand: yes

  proxied2:
    source: rtsp://rtsp.stream/pattern
    sourceOnDemand: yes
```

The testauth endpoint is a simple nodejs express server.
When opening one of the streams using HLS with Chrome, the server will call the auth api endpoint, but the POST request will be empty.

Can you confirm this behaviour? Or am I missing something?

## Describe how to replicate the issue

1. Start docker container
docker run --rm -it --network=host -v $PWD/rtsp-test.yml:/rtsp-simple-server.yml:ro aler9/rtsp-simple-server 

2. Open the resulting HLS stream in Chrome
http://myip/proxied2
3. The authentication endpoint will receive a POST request from the server, but with an empty body
4. If the auth server will return 200, the stream will load
5. If the auth server will return 401, the basic auth dialog will be shown in the browser. When accepted, the auth server will receive another empty POST request. The stream will not be loaded in the end. 
The server will log `[HLS] [muxer proxied2] authentication error: external authentication failed: bad status code: 401`

## Did you attach the server logs?

 no

## Did you attach a network dump?

no
