### ISSUE TITLE
Proxied LL-HLS stream stops after ~24 hours

### ISSUE THREAD

**Issue by OlliePugh** [aler9/rtsp-simple-server#1289]
## Which version are you using?

v0.20.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I have the following architecture for a video stream

![image](https://user-images.githubusercontent.com/25775112/206656327-5e019889-9c8f-45f8-9bd2-f20527fc99e3.png)

The stream works perfectly fine for the first ~24 hours and then after that if you load the page, the video will not load (using HLS.js) it also doesn't work if you use the page that `rtsp-simple-proxy` offers to view it (which also uses hls.js)

The on prem server is also running rtsp-stream but the stream never drops, if the LL-HLS from the proxy stops working, I can still view the RTSP stream from the on prem server so I don't think the issue lies there. 

The only logs I am seeing from the proxy VM's are the following: 

[downloaded-logs-20221209-082041.txt](https://github.com/aler9/rtsp-simple-server/files/10193047/downloaded-logs-20221209-082041.txt)
(Sorry for the funny format, google cloud doesn't offer great export options for logs)
If those logs are not sufficient is there a setting I can enable to produce more?

I have removed the box from the load balancer and left it running so you can still see what data the server is outputting. address for the stream is: https://34.88.200.87/proxied/.

The server still responds with m3u8 files and sends chunks, unfortunately I do not understand HLS well enough to know if they are correct!

My config file for the proxies are the following: 
```
###############################################
# General parameters

logLevel: info
logDestinations: [stdout]
logFile: rtsp-simple-server.log

readTimeout: 10s
writeTimeout: 10s
readBufferCount: 1024

externalAuthenticationURL:

api: no
apiAddress: 127.0.0.1:9997

metrics: nor.
metricsAddress: 127.0.0.1:9998

pprof: no
pprofAddress: 127.0.0.1:9999

runOnConnect:
runOnConnectRestart: no

###############################################
# RTSP parameters

rtspDisable: no
protocols: [udp, multicast, tcp]
encryption: "no"
rtspAddress: :8554
rtspsAddress: :8322
rtpAddress: :8000
rtcpAddress: :8001
multicastIPRange: 224.1.0.0/16
multicastRTPPort: 8002
multicastRTCPPort: 8003
serverKey: server.key
serverCert: server.crt
authMethods: [basic, digest]

###############################################
# RTMP parameters

rtmpDisable: yes
rtmpAddress: :1935
rtmpEncryption: "no"
rtmpsAddress: :1936
rtmpServerKey: server.key
rtmpServerCert: server.crt

###############################################
# HLS parameters
hlsDisable: no
hlsAddress: :443
hlsAlwaysRemux: yes
hlsVariant: lowLatency
hlsSegmentCount: 7
hlsSegmentDuration: 1s
hlsPartDuration: 500ms
hlsSegmentMaxSize: 50M
hlsAllowOrigin: "*"
hlsEncryption: yes
hlsServerKey: server.key
hlsServerCert: server.crt
hlsTrustedProxies: []

###############################################
# Path parameters
paths:
  proxied:
    # url of the source stream, in the format rtsp://user:pass@host:port/path
    source: rtsp://{on-prem-ip}:8554/cam
    sourceProtocol: tcp
```

I am sure I have missed some crucial information so let me know if I can provide anything more 🤣
