### ISSUE TITLE
I am getting a segmantation fault if using the rpi-camera

### ISSUE THREAD

**Issue by 10k-resistor** [aler9/rtsp-simple-server#1346]
## Which version are you using?

v0.21.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [X] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

I am using a raspberry pi zero w and a raspberrypi-camera.
Docker version 20.10.22

## Describe the issue

I am getting the follwoing error: `simple-rtsp-server    | 2022/12/30 17:45:07 INF [path cam] [rpicamera source] ERR: signal: segmentation fault (core dumped)`

I have tried it with enabled an disabled legacy camera-support which makes no difference. The camera works with other tools like fswebcam.
It works when running the rtsp-simple-server without docker.

## Describe how to replicate the issue

Use this docker-compose file:
```yaml
version: '3'
services:  
simple-rtsp-server:
    image: aler9/rtsp-simple-server:latest-rpi
    container_name: simple-rtsp-server
    privileged: true
    tmpfs: '/dev/shm:exec'
    environment:
      - RTSP_PROTOCOLS=tcp
      - RTSP_PATHS_CAM_SOURCE=rpiCamera
#    ports:
#      - 8554:8554
#      - 1935:1935
#      - 8888:8888
    network_mode: host
    volumes:
      - type: bind
        source: /data/docker/simple-rtsp-server/config-simple-rtsp-server.yaml
        target: /rtsp-simple-server.yml
      - /run/udev:/run/udev:ro
```
Run `docker-compose up`
## Did you attach the server logs?
yes [log.txt](https://github.com/aler9/rtsp-simple-server/files/10325905/log.txt)

## Did you attach a network dump? 
no
