### ISSUE TITLE
runOn to update list of streams

### ISSUE THREAD

**Issue by williamelliott1** [aler9/rtsp-simple-server#1352]
## Describe the feature

I am creating a webapp to view the server's streams.  To get the list of active streams I can poll the api but I'd prefer a runOn hook that is called whenever a stream is set up or torn down.  I dont think this currently exists (specifically when a path is torn down) but if it does, please let me know.  Thank you!

**Comment by aler9** [comment]
Hello, `runOnReady` already allows to do this:

```yml
paths:
  mypath:
    source: publisher or rtsp://
    runOnReady: /myscript.sh
```

content of `myscript.sh`:

```sh
#!/bin/sh
trap "stream is not ready anymore" INT
echo stream is ready
sleep 86400
```
