### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by daanschenkel** [aler9/rtsp-simple-server#1509]
## Describe the feature

Hi, is there any way to add a custom logo in the top left corner? If not, can it be added?

**Comment by 0x-a6** [comment]
Wouldn't you just put a watermark with your chosen streaming source into the server, eg. GStreamer, add a freeze image into the pipeline then videomux to the output to the RTSP?

Use [chat.openai.com ](https://chat.openai.com/chat) and enter in your pipeline question to see if it can give you some example to help?

**Comment by aler9** [comment]
Hello, you can add a logo to a video stream by using FFmpeg inside the `runOnReady` setting:

```yml
paths:
  original:
    runOnReady: ffmpeg -i rtsp://localhost:8554/original -i logo.png -filter_complex "overlay=5:5" -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:8554/branded

  branded:
```

Publish a video stream to path `/original` and you'll see the stream with the custom logo in path `/branded`.

For more complex usage, take a look at the documentation of the overlay filter of FFmpeg.
