### ISSUE TITLE
Compression via ffmpeg only on demand

### ISSUE THREAD

**Issue by forabi** [aler9/rtsp-simple-server#1541]
## Describe the feature

Description
The README has instructions on how to do a compressed stream via runOnReady. I assume this means ffmpeg will unconditionally run whether there are consumers for the compressed stream or not. This starts to slowdown my Pi 4 with just two stream (I have a bunch of other stuff running, of course). 

My question/request is: can I start and kill the compressed stream based on whether it's being used or not?

**Comment by raypanggh** [comment]
Look at runOnDemand. It's explained in the config file

**Comment by forabi** [comment]
Run on demand does not work with startOnReady

**Comment by forabi** [comment]
Even if it did, the compressed stream would be started when the raw stream
is accessed. This is not efficient. I want the compressed stream to only
start when it's actually requested and shut down when it's not used.

**Comment by forabi** [comment]
Ffmpeg will start compressing the stream when the _raw_ stream is
requested. I don't want to compress the stream if the compressed version is
not being used.

**Comment by raypanggh** [comment]
Can you share your config so I can understand the use case?

**Comment by forabi** [comment]
This is an example of one stream that I need a compressed version of. As you can see, `runOnReady` is started when the _uncompressed_ stream is ready. If I combine `sourceOnDemand` with `runOnReady`, the compressed stream won't start unless the raw stream is requested. That does not make sense. Also, we cannot control ffmpeg to only compress on demand because it's started from the raw stream, not from the compressed path.

```yml
paths:
 all:
   publishUser: <redacted>
   publishPass: <redacted>
 1/unicast/compressed:
  readUser: <redacted>
  readPass: <redacted>
 1/unicast:
   readUser: root
   readPass: <redacted>
   source: rtsp://root:<redacted>@<ip>:8554/unicast
   sourceOnDemand: no
   sourceProtocol: udp
   runOnReady: ffmpeg -i rtsp://<redacted>:<redacted>@localhost:$RTSP_PORT/$RTSP_PATH -c:v h264_v4l2m2m -b:v 600k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_P>
   runOnReadyRestart: yes
```

**Comment by raypanggh** [comment]
Could you not make 1/unicast simply an RTSP proxy for rtsp://root:<redacted>@<ip>:8554/unicast, and then have 1/unicast/compressed call ffmpeg via runOnDemand?

I'm imagining this:

```
1/unicast/compressed:
  runOnDemand: ffmpeg -i rtsp://<redacted>:<redacted>@localhost:$RTSP_PORT/1/unicast -c:v h264_v4l2m2m -b:v 600k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
  runOnDemandRestart: yes
1/unicast:
   source: rtsp://root:<redacted>@<ip>:8554/unicast
   sourceOnDemand: no # or yes if you don't want the bandwidth consumption if nobody is using the uncompressed source
   sourceProtocol: udp
```

This way the 1/unicast (the uncompressed stream) is always available, and only if 1/unicast/compressed is requested does ffmpeg kick in.

**Comment by forabi** [comment]
Tried it, but it didn't work:

```
Mar 15 16:57:50 raspberrypi rtsp-simple-server[5540]: 2023/03/15 16:57:50 INF [RTSP] [conn 192.168.0.168:56752] closed (no one is publishing to path '3/unicast/compressed')
```

**Comment by forabi** [comment]
```
 3/unicast/compressed:
  readUser: <redacted>
  readPass: <redacted>
  runOnReady: ffmpeg -i rtsp://<redacted>:<redacted>@localhost:$RTSP_PORT/3/unicast -c:v h264_v4l2m2m -b:v 600k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
  runOnReadyRestart: yes
 3/unicast:
   readUser: <redacted>
   readPass: <redacted>
   source: rtsp://<redacted>:<redacted>@<ip>:8554/unicast
   sourceOnDemand: yes
   sourceProtocol: udp
```

Am I doing something wrong?
