### ISSUE TITLE
ERR: a path with a regular expression (or path 'all') cannot have a RTSP source; use another path

### ISSUE THREAD

**Issue by motogon** [aler9/rtsp-simple-server#175]
ERR: a path with a regular expression (or path 'all') cannot have a RTSP source; use another path

## Which version are you using?

v0.13.1

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [ x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

config : 

source: "rtsp://xxxxx:xxxxxxxx@192.168.3.109:554/cam/realmonitor?channel=1&subtype=0"

**Comment by aler9** [comment]
Like the error message is saying, use another path. The "all" path applies to all paths, if sources would be allowed, they would be exposed on every path, while they must be exposed on a specific path.

```yml
paths:
  mypath:
    source: "rtsp://xxxxx:xxxxxxxx@192.168.3.109:554/cam/realmonitor?channel=1&subtype=0"
```
