### ISSUE TITLE
Is there a way to remux or re-encode in RTSP proxy mode?

### ISSUE THREAD

**Issue by michaelmohamed-anno** [aler9/rtsp-simple-server#177]
## Which version are you using?

Latest

## Question
Is there a way to remux or re-encode in RTSP proxy mode?

Description

The RTSP proxy mode works well for my use case. I would like to proxy a re-encoded version using libx264rgb instead of libx264.

**Comment by aler9** [comment]
Hello, yes, of course, just start the conversion on another path with `runOnInit` and set the `restart` parameter to yes, in order to account for eventual disconnections

```yml
paths:
  proxied:
    source: rtsp://originalurl

  converted:
    runOnInit: ffmpeg -i rtsp://localhost:$RTSP_PORT/proxied -c:v libx264 -preset ultrafast -b:v 500k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/converted
    runOnInitRestart: yes
```
