### ISSUE TITLE
How to add a rtsp from ip camera as a source 

### ISSUE THREAD

**Issue by ithouse98** [aler9/rtsp-simple-server#188]
## Which version are you using?

v0.13.2

## Question

Hi i want to add a rtsp url from ip camera for relaying rtsp .
my question is : where i put my rtsp url as input source ?

**Comment by x-jokay** [comment]
I use it for the exact same use case. This is a sample `docker-compose.yml`.

```yml
version: '3.8'

services:
  app:
    image: docker.io/aler9/rtsp-simple-server:latest
    environment:
      - TZ=Europe/Zurich
      - RTSP_PROTOCOLS=udp
      - RTSP_RTSPPORT=55555
      - RTSP_RTPPORT=55556
      - RTSP_RTCPPORT=55557
      - RTSP_READTIMEOUT=10s
      - RTSP_WRITETIMEOUT=10s
      - RTSP_PATHS_ALL_READUSER={username}
      - RTSP_PATHS_ALL_READPASS={password}
      - RTSP_PATHS_CAM1_SOURCE=rtsp://{cam-username}:{cam-password}@{cam-ip}:{cam-rtsp-port}/cam/realmonitor?channel=1&subtype=0
      - RTSP_PATHS_CAM1_SOURCEPROTOCOL=udp
      - RTSP_PATHS_CAM1_SOURCEONDEMAND=yes
    network_mode: "host"
```
