### ISSUE TITLE
TCP mode not compatible with GStreamer rtsp defaults

### ISSUE THREAD

**Issue by dorinclisu** [aler9/rtsp-simple-server#198]
## Which version are you using?
v0.12.2 - v0.14.0

## Which operating system are you using?
- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture
- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue
GStreamer rtspsrc protocol defaults are `udp, udp-mcast, tcp` and they are tried in this order. When the rtsp server is restricted to TCP, gstreamer does the following:
 - Tries first udp, rtsp server replies that udp is disabled (good)
 - Tries udp-mcast, **rtsp server replies with 400** (probably incorrect behavior)
 - Doesn't have the chance to try tcp

## Replicate
``` 
authMethods:
- basic
- digest
encryption: false
logDestinations:
- stdout
logFile: rtsp-simple-server.log
logLevel: info
metrics: false
pprof: false
protocols:
- tcp
readTimeout: 10s
rtcpPort: 8001
rtpPort: 8000
rtspPort: 8554
rtspsPort: 8555
runOnConnectRestart: false
serverCert: server.crt
serverKey: server.key
writeTimeout: 10s
paths:
  test:
    source: rtsp://user:pass@x.x.x.x/path
    sourceOnDemand: true
    sourceProtocol: tcp
```

```
docker run -it --rm -p 554:8554 -v $PWD/rtsp-simple-server.yml:/root/rtsp-simple-server.yml aler9/rtsp-simple-server:v0.14.0 root/rtsp-simple-server.yml
2021/02/03 09:51:41 [I] [0/0/0] rtsp-simple-server v0.14.0
2021/02/03 09:51:41 [I] [0/0/0] [TCP/RTSP listener] opened on :8554
2021/02/03 09:51:49 [I] [1/0/0] [client 172.17.0.1:58570] connected (plain)
2021/02/03 09:51:49 [I] [1/0/0] [path test] [rtsp source] started
2021/02/03 09:51:49 [I] [1/0/0] [path test] [rtsp source] connecting
2021/02/03 09:51:51 [I] [1/0/0] [path test] [rtsp source] ready
2021/02/03 09:51:51 [I] [1/0/0] [client 172.17.0.1:58570] ERR: multicast is not supported
2021/02/03 09:51:51 [I] [0/0/0] [client 172.17.0.1:58570] disconnected
```

```
gst-launch-1.0 rtspsrc location='rtsp://localhost/test' ! fakesink
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Progress: (open) Opening Stream
Progress: (connect) Connecting to rtsp://192.168.1.4:554/test
Progress: (open) Retrieving server options
Progress: (open) Retrieving media info
Progress: (request) SETUP stream 0
Progress: (request) SETUP stream 0
ERROR: from element /GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0: Could not write to resource.
Additional debug info:
gstrtspsrc.c(7019): gst_rtspsrc_setup_streams_start (): /GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0:
Error (400): Bad Request
ERROR: pipeline doesn't want to preroll.
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
```

## Workarounds
- Disabling udp-multicast in gstreamer (explicitly allowing only udp and tcp):
```
gst-launch-1.0 rtspsrc location='rtsp://localhost/test' protocols=udp+tcp ! fakesink
```
- Allowing udp in rtsp server
```
protocols:
- tcp
- udp
```
But udp is usually problematic for many reasons (NAT firewalls, docker, TLS) which is why I had disabled it.
I think both workarounds are not beginner friendly because they involve non-intuitive system behavior, and I think the server should work with gstreamer defaults.

## Proposed solution
Instead of replying with 400 when udp-mcast is tried, rtsp server should give the same reply as when udp is tried but disabled in yml config.
