### ISSUE TITLE
Forward RTMP Stream to external RTMP Server

### ISSUE THREAD

**Issue by onthegit** [aler9/rtsp-simple-server#203]
## Question

Hello, thanks for the project.  I have a question for which I could not find an answer in the docs.
How to forward RTMP stream to external RTMP servers?
Do we need to pipe the stream via ffmpeg to other rtmp servers or rtsp-simple-server has this capability (without ffmpeg)

OBS -> rtsp-simple-server -> google rtmp, twitch rtmp ?

Thank you.

**Comment by onthegit** [comment]
Can the following be used but for RTMP (not RTSP):
paths:
  redirected:
    source: redirect
    sourceRedirect: rtmp://otherurl/otherpath

**Comment by aler9** [comment]
Hello,

1. use this configuration:

```yml
paths:
  redirected:
    runOnPublish: ffmpeg -re -i rtsp://localhost:8554/redirected -c copy -f flv rtmp://otherurl/otherpath
```

2. launch the server

3. use this URL in OBS

```
rtmp://rtsp-simple-server-ip/redirected
```

be careful that you need ffmpeg installed too.
