### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by aler9** [aler9/rtsp-simple-server#21]
Ported from https://github.com/aler9/rtsp-simple-proxy/issues/9

**Comment by x-jokay** [comment]
How to transform the `rtsp-simple-proxy` config:

```yml
...

streams:
  cam1:
    url: rtsp://user1:pass1@192.168.1.10:554/stream1
    protocol: udp
  cam2:
    url: rtsp://user2:pass2@192.168.2.10:554/stream1
    protocol: tcp
  cam3:
    url: rtsp://user3:pass3@192.168.3.10:554/stream1
    protocol: udp
```

to the `rtsp-simple-server` config?

```yml
paths:
  all:
    # source of the stream - this can be:
    # * record -> the stream is provided by a client through the RECORD command (like ffmpeg)
    # * rtsp://url -> the stream is pulled from another RTSP server
    source: record
    # if the source is an RTSP url, this is the protocol that will be used to pull the stream
    sourceProtocol: udp

    # username required to publish
    publishUser:
    # password required to publish
    publishPass:
    # IPs or networks (x.x.x.x/24) allowed to publish
    publishIps: []

    # username required to read
    readUser:
    # password required to read
    readPass:
    # IPs or networks (x.x.x.x/24) allowed to read
    readIps: []
```

**Comment by x-jokay** [comment]
Like this?

```yml
paths:
  all:
    readUser: view
    readPass: view-pass
  cam1:
    url: rtsp://user1:pass1@192.168.1.10:554/stream1
    protocol: udp
  cam2:
    url: rtsp://user2:pass2@192.168.2.10:554/stream1
    protocol: tcp
  cam3:
    url: rtsp://user3:pass3@192.168.3.10:554/stream1
    protocol: udp
```
