### ISSUE TITLE
ASK about  proxy feature

### ISSUE THREAD

**Issue by x09** [aler9/rtsp-simple-server#220]
I have a question.
With your software i can proxied video from camera from localnet to global net?

Something like this ?
![Диаграмма1](https://user-images.githubusercontent.com/1303927/108823890-dade6a00-75e2-11eb-8312-22d4f2c3e0fc.png)

I need install software to Raspberry and VPS ?

**Comment by aler9** [comment]
Hello, of course it's possible, you have to
1. install rtsp-simple-server on the raspberry pi, and configure it in this way
    ```yml
    paths:
      camera:
        source: rtsp://192.168.0.200:554/path
        runOnInit: ffmpeg -i rtsp://localhost:8554/camera -c copy -f rtsp rtsp://mysuperserver.com:8554/camera
        runOnInitRestart: yes
    ```
    
2. install rtsp-simple-server on mysuperserver.com
