### ISSUE TITLE
[QUESTION] - Source RTSP proxy to HLS in docker

### ISSUE THREAD

**Issue by vitorcampea** [aler9/rtsp-simple-server#347]
Hello,

This is a cool project.
I am trying to broadcast all multiple RTSP CCTVS to HLS but I am failing.

Right now I can already fetch one stream and restream it with a proxy, as follows.
I am using a public rtsp sample.

docker-compose
```
version: '3.7'

services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: nginx
    ports:
      - '8090:80'
    volumes:
      - ./app:/usr/share/nginx/
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  rtsp-simple-server:
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8554:8554'
      - '1935:1935'
    volumes:
      - ./conf/rtsp/rtsp-simple-server.yml:/rtsp-simple-server.yml
    image: aler9/rtsp-simple-server
```

i pass my yml configuration via docker volume and using the proxy example on documentation.
If i use the VLC client, it work perfectly, but how can i configure this to HLS?

rtsp-simple-server.yml
```
paths:
  proxied:
    # url of the source stream, in the format rtsp://user:pass@host:port/path
    source: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
    sourceOnDemand: yes
```

I am trying to follow the HLS tutorial but not working.... i don't know where they the stream.m3u8 are located
https://github.com/aler9/rtsp-simple-server#convert-streams-to-hls

It is possible to broadcast like 20 cctvs to HLS in docker? (if this could be on demand, ever better)
After i get the m3u8 i could expose them with a nginx container

I would thank you for the help!

Best Regards
