### ISSUE TITLE
Segmentation violation - gortsplib.(*ClientConn).backgroundPlayTCP

### ISSUE THREAD

**Issue by dorinclisu** [aler9/rtsp-simple-server#348]
## Which version are you using?

v0.15.0 - v0.15.4

## Which operating system are you using?

OS
- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture
- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue
It does not appear to be triggered by something specific, instead it works for a few hours / days and then it crashes. Usual RAM and CPU usage never exceed 50%. But after crash the CPU stays at 100% and the process hangs.
```
2021-04-11T08:50:52.546331155Z [I] [57/0/25] [client A.B.C.D:54120] is reading from path 'path123', 1 track with tcp
2021-04-11T08:50:52.551534607Z error: invalid memory address or nil pointer dereference
2021-04-11T08:50:52.552695839Z segmentation violation code=0x1 addr=0x10 pc=0x6f481a]
2021-04-11T08:50:52.553570163Z [running]:
2021-04-11T08:50:52.557716154Z 0x8edfa007d14e, 0xcc5880, 0x0, 0xc00da32800, 0x5, 0x2710)
2021-04-11T08:50:52.559239354Z 0xc002159c10)
2021-04-11T08:50:52.560232505Z github.com/aler9/gortsplib.(*ClientConn).backgroundPlayTCP
```

There is no way to replicate yet. I have 2 identical instances of the server, one with under 10 streams, and one with about 200 (out of which max 64 are active at a time). This issue NEVER occured with the small instance.

This is a template of the configuration:
```
authMethods: [digest]
readBufferSize: 10000
readBufferCount: 512
encryption: false
logDestinations: [stdout]
logFile: rtsp-simple-server.log
logLevel: info
metrics: false
pprof: false
protocols: [tcp, udp]
readTimeout: 10s
rtmpDisable: yes
rtcpPort: 8001
rtpPort: 8000
rtspPort: 554
rtspsPort: 555
runOnConnectRestart: false
serverCert: server.crt
serverKey: server.key
writeTimeout: 10s
paths:
  TEMPLATE:
    source: rtsp://...
    readIps: ['A.B.C.D', 'W.X.Y.Z']
    readUser: user
    readPass: pass
    sourceOnDemand: true
    sourceProtocol: tcp
  all:
    source: record
    publishUser: pubuser
    publishPass: pubpass
    readIps: ['A.B.C.D', 'W.X.Y.Z']
    readUser: user
    readPass: pass
    runOnDemandCloseAfter: 10s
    runOnDemandRestart: false
    runOnDemandStartTimeout: 10s
    runOnInitRestart: false
    runOnPublishRestart: false
    runOnReadRestart: false
    sourceProtocol: automatic
```

## Did you attach a network dump?
No, because it's not replicable.
