### ISSUE TITLE
When I was having gst-launch-1.0 send an rtspclient stream to simple-rtsp-server,I can't play it using gst-launch-1.0

### ISSUE THREAD

**Issue by javyxu** [aler9/rtsp-simple-server#358]
## Which version are you using?

v0.15.5

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

ubuntu 18.04 
gststreamer 1.14.5

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

Hello, I made the following configuration according to the documentation:

```yaml
cam:
    runOnInit: gst-launch-1.0 rtspsrc location=rtsp://127.0.0.1:8554/5E protocols=tcp ! rtph264depay ! h264parse ! avdec_h264 ! autovideoconvert ! rtspclientsink location=rtsp://127.0.0.1:8554/test protocols=tcp
    runOnInitRestart: yes
```

then start the service，and output the following information

![image](https://user-images.githubusercontent.com/22185273/115205346-0cc80480-a12c-11eb-8721-8813bd5f102b.png)

Next, I use the **gst-launch-1.0 playbin uri=rtsp://127.0.0.1:8554/test** can't play video properly，but to use **gst-launch-1.0 playbin uri=rtsp://127.0.0.1:8554/5E** is normal。

Do you have a good solution, thank you !!!
