### ISSUE TITLE
Authentication Doesn't Work - ERR: critical authentication error

### ISSUE THREAD

**Issue by eugenedw** [aler9/rtsp-simple-server#370]
The instructions are pretty straightforward. I don't think I've done anything wrong here, but after setting up a "publishUser" and "publishPass" on a stream path, I'm receiving authentication errors from the client. I've tried using both the plain text and SHA256 (to base 64) hash and neither work. To see whether it may have been the client (OBS Studio), I created an ECamm account and same outcome, "ERR: critical authentication error".

Am I missing something?

Here's the setup:

```
paths:
  testpath1:
    publishUser: sha256:nvQVCltqbawcRPRSxpKhS8nPvZrhnuXhipICkSgM3EA=
    publishPass: sha256:PUG8KwZbpC+Ncb7EKkJ+DDsVBTpIbLsin1ecCN/lKlg=
  testpath2:
    publishUser: username
    publishPass: password
```
