### ISSUE TITLE
ERR: fmtp attribute is missing

### ISSUE THREAD

**Issue by coute** [aler9/rtsp-simple-server#411]
## Which version are you using?

v0.16.2

## Which operating system are you using?

OS

- [ x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [ x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

I pull a rtsp stream form a webcam and try to watch it with HLS

## Describe how to replicate the issue
conf
```
logLevel: info
logDestinations: [stdout]
logFile: rtsp-simple-server.log

readTimeout: 60s
writeTimeout: 60s
readBufferCount: 512

metrics: no
metricsAddress: :9998

pprof: no
pprofAddress: :9999

runOnConnect:
runOnConnectRestart: no

rtspDisable: no
protocols: [tcp]
encryption: no
rtspAddress: :8554
rtspsAddress: :8555
rtpAddress: :8000
rtcpAddress: :8001
serverKey: server.key
serverCert: server.crt
authMethods: [basic, digest]
readBufferSize: 2048

rtmpDisable: yes
rtmpAddress: :1935

hlsDisable: no
hlsAddress: :8888
hlsSegmentCount: 5
hlsSegmentDuration: 5s

paths:
  cam:
    source: rtsp://myurl
```

Try to watch the path with Chrome : http://localhost:8888/cam

I had this error:
```
2021/06/03 11:23:03 I [1/1] [HLS] [converter cam] opened
2021/06/03 11:23:03 I [1/1] [HLS] [converter cam] ERR: fmtp attribute is missing
2021/06/03 11:23:03 I [1/1] [HLS] [converter cam] closed
```

In packet 11 of the dump, the camera describe the session :
```
[rtsp @ 0x7feb5c000b80] SDP:aq=    0KB vq=    0KB sq=    0B f=0/0
v=0
o=- 1361 1 IN IP4 192.168.1.203
s=RTSP Server
c=IN IP4 0.0.0.0
t=0 0
a=range:npt=now-
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=control:rtsp://myurl:5543/LiveMedia/ch1/Media2/trackID=1
a=recvonly
```
fmtp attribute is missing in RTP session
A line should be something like that :
`a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAH6zZgFAFuwEQAAADABAAAAMBQPGDGaA=,aMlgIyyL; profile-level-id=64001F`

I can't modify the camera to add this attriubte.
Can you have a look how to skip that ?
Thanks.

## Did you attach a network dump?

yes
[dump.zip](https://github.com/aler9/rtsp-simple-server/files/6591525/dump.zip)
