### ISSUE TITLE
Move Docker rtsp-simple-server.yml config file from root path to a sub-path

### ISSUE THREAD

**Issue by hagak** [aler9/rtsp-simple-server#419]
## Describe the feature
Currently rtsp-simple-server.yml resides at the root of the docker image which means if you want to override it with a local file you have to mount just the file.  This does not work if your files are on a volume like NFS since you can not "mount" a single file.  If this file was moved to a sub folder by itself then it would allow using NFS volumes for the config file.

**Comment by dorinclisu** [comment]
You can mount anywhere and pass the yml config file path as argument to the executable.

**Comment by aler9** [comment]
Just use the `arg` parameter and point to the desired configuration file.

```yml

- apiVersion: v1
  kind: Deployment
  metadata:
    name: videoproxy
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: videoproxy
    template:
      metadata:
        labels:
          app: videoproxy
      spec:
        containers:
        - name: main
          image: aler9/rtsp-simple-server
          args: ["/mynfsfolder/rtsp-simple-server.yml"]
```
