### ISSUE TITLE
FFmpeg Restream RTSP with overlay windows

### ISSUE THREAD

**Issue by Tabarane** [aler9/rtsp-simple-server#460]
### Discussed in https://github.com/aler9/rtsp-simple-server/discussions/459

<div type='discussions-op-text'>

<sup>Originally posted by **Tabarane** July  8, 2021</sup>
Hi, im trying to use RTSP Simple server to re-stream an RTSP with an overlay and controlled bitrate over windows

issue is the stream don't start from ffmpeg side and per so , the server can not stream the path required

below you can see my configuration

```
paths:
  scope:
   runOnDemand: ffmpeg -i rtsp://192.168.1.1:554/live -i "C:\overlay.png" -filter_complex "overlay=(W-w)/2:(H-h)/2" -c:v libx264 -preset ultrafast -b:v 1500k -max_muxing_queue_size 4096 -f rtsp rtsp://0.0.0.0:$RTSP_PORT/$RTSP_PATH
   runOnDemandRestart: yes
```

Note:
If we try to connect with the source RTSP via TCP protocol, i get error 461 , so basically the source need to be connected via UDP but the simple server re-stream should be TCP, same command over Ubuntu works without issues, but windows does not work</div>
