### ISSUE TITLE
Authentication - multiple read users

### ISSUE THREAD

**Issue by claudemangen** [aler9/rtsp-simple-server#462]
Hello,

is there a possibility to set for each stream an authentication for multiple users?

We have a lot of cameras and would like to give access to some of them temporarily to certain users. To not always send a new password to all the other users this would help a lot.

Thank you in advanced

Best regards

**Comment by bottlehall** [comment]
I'm new to using this, but would setting up multiple ['proxy mode'](https://github.com/aler9/rtsp-simple-server#proxy-mode) paths solve your problem? Reading the documentation suggests you can set up different authentication for each path (admittedly the example is under `all:` so I may be wrong). So, your primary group would use one set of credentials and then you could add/remove others as you need them. I haven't got time to test it, but this would seem a sensible stab at it:

``` 
paths:
  temporary0:
    source: rtsp://original-url
    readUser: user0
    readPass: userpass0
  temporary1:
    source: rtsp://original-url
    readUser: user1
    readPass: userpass1
```

You could protect your original path with credentials for your permanent users.

Hope this helps.
