### ISSUE TITLE
Question: Can I use runOnPublish option with dynamic url

### ISSUE THREAD

**Issue by LuiGee3471** [aler9/rtsp-simple-server#47]
I'm trying to save input rtsp as another video file, but it seems I can only specify one url when I'm using ffmpeg on runOnPublish option.

Is there an way to use its own rtsp url from input as variable?

**Comment by aler9** [comment]
Hello, variables inside runOnPublish / runOnRead / runOnDemand will be supported soon.

**Comment by LuiGee3471** [comment]
Good to hear that. Looking forward to it.

**Comment by aler9** [comment]
Hello, this should be implemented in v0.9.9 - use a configuration like this:
```yaml
paths:
  all:
    runOnPublish: ffmpeg -i rtsp://localhost:8554/$RTSP_SERVER_PATH -c copy -f mpegts myfile.ts
```
