### ISSUE TITLE
api port binding isn't working with docker

### ISSUE THREAD

**Issue by Pulpyyyy** [aler9/rtsp-simple-server#520]
v0.17.2 / Linux / arm64

Hello,

Running application with same config file on both docker an compiled release doesn't have the same behavior.
Api does not bind (and maybe stop source connection)
Here is config file

```

###############################################
# General parameters

# sets the verbosity of the program; available values are "warn", "info", "debug".
logLevel: debug
# destinations of log messages; available values are "stdout", "file" and "syslog".
logDestinations: [stdout]
# if "file" is in logDestinations, this is the file which will receive the logs.
logFile: rtsp-simple-server.log

# timeout of read operations.
readTimeout: 10s
# timeout of write operations.
writeTimeout: 10s
# number of read buffers.
# a higher number allows a higher throughput,
# a lower number allows to save RAM.
readBufferCount: 100000

# enable the HTTP API.
api: yes
# address of the API listener.
apiAddress: 0.0.0.0:9997

# enable Prometheus-compatible metrics.
metrics: no
# address of the metrics listener.
metricsAddress: 0.0.0.0:9998

# enable pprof-compatible endpoint to monitor performances.
pprof: no
# address of the pprof listener.
pprofAddress: 0.0.0.0:9999

# command to run when a client connects to the server.
# this is terminated with SIGINT when a client disconnects from the server.
# the server port is available in the RTSP_PORT variable.
runOnConnect:
# the restart parameter allows to restart the command if it exits suddenly.
runOnConnectRestart: no

###############################################
# RTSP parameters

# disable support for the RTSP protocol.
rtspDisable: no
# supported RTSP stream protocols.
# UDP is the most performant, but doesn't work when there's a NAT/firewall between
# server and clients, and doesn't support encryption.
# UDP-multicast allows to save bandwidth when clients are all in the same LAN.
# TCP is the most versatile, and does support encryption.
# The handshake is always performed with TCP.
protocols: [udp, multicast, tcp]
# encrypt handshake and TCP streams with TLS (RTSPS).
# available values are "no", "strict", "optional".
encryption: no
# address of the TCP/RTSP listener. This is needed only when encryption is "no" or "optional".
rtspAddress: 0.0.0.0:8554
# address of the TCP/TLS/RTSPS listener. This is needed only when encryption is "strict" or "optional".
rtspsAddress: :8555
# address of the UDP/RTP listener. This is needed only when "udp" is in protocols.
rtpAddress: :8000
# address of the UDP/RTCP listener. This is needed only when "udp" is in protocols.
rtcpAddress: :8001
# IP range of all UDP-multicast listeners. This is needed only when "multicast" is in protocols.
multicastIPRange: 224.1.0.0/16
# port of all UDP-multicast/RTP listeners. This is needed only when "multicast" is in protocols.
multicastRTPPort: 8002
# port of all UDP-multicast/RTCP listeners. This is needed only when "multicast" is in protocols.
multicastRTCPPort: 8003
# path to the server key. This is needed only when encryption is "strict" or "optional".
# this can be generated with:
# openssl genrsa -out server.key 2048
# openssl req -new -x509 -sha256 -key server.key -out server.crt -days 3650
serverKey: server.key
# path to the server certificate. This is needed only when encryption is "strict" or "optional".
serverCert: server.crt
# authentication methods.
authMethods: [basic, digest]
# read buffer size.
# this doesn't influence throughput and shouldn't be touched unless the server
# reports errors about the buffer size.
readBufferSize: 2048

###############################################
# RTMP parameters

# disable support for the RTMP protocol.
rtmpDisable: no
# address of the RTMP listener.
rtmpAddress: :1935

###############################################
# HLS parameters

# disable support for the HLS protocol.
hlsDisable: no
# address of the HLS listener.
hlsAddress: :8888
# by default, HLS is generated only when requested by a user;
# this option allows to generate it always, avoiding an initial delay.
hlsAlwaysRemux: no
# number of HLS segments to generate.
# increasing segments allows more buffering,
# decreasing segments decreases latency.
hlsSegmentCount: 3
# minimum duration of each segment.
# the final segment duration is also influenced by the interval between IDR frames,
# since the server changes the segment duration to include at least a IDR frame in each one.
hlsSegmentDuration: 1s
# value of the Access-Control-Allow-Origin header provided in every HTTP response.
# This allows to play the HLS stream from an external website.
hlsAllowOrigin: '*'

###############################################
# Path parameters
paths:
  contre-allee:
    source: rtsp://192.168.1.60:554/stream0?username=admin&password=password
    runOnPublish:
    runOnPublishRestart: yes
    readUser: adm
    readPass: pass
```
On docker : 
```
Starting frigate_rtsp-simple-server_1 ... done
Attaching to frigate_rtsp-simple-server_1
rtsp-simple-server_1  | 2021/08/18 21:28:35 I [0/0] rtsp-simple-server v0.17.2
rtsp-simple-server_1  | 2021/08/18 21:28:35 I [0/0] [RTSP] UDP/RTP listener opened on :8000
rtsp-simple-server_1  | 2021/08/18 21:28:35 I [0/0] [RTSP] UDP/RTCP listener opened on :8001
rtsp-simple-server_1  | 2021/08/18 21:28:35 I [0/0] [RTSP] TCP listener opened on :8554
rtsp-simple-server_1  | 2021/08/18 21:28:35 I [0/0] [RTMP] listener opened on :1935
rtsp-simple-server_1  | 2021/08/18 21:28:35 I [0/0] [HLS] listener opened on :8888
```
vlc can't connect
```
rtsp-simple-server_1  | 2021/08/18 21:35:16 I [0/0] [RTSP] [conn 192.168.1.10:60198] opened
rtsp-simple-server_1  | 2021/08/18 21:35:16 I [0/0] [path contre-allee] created
rtsp-simple-server_1  | 2021/08/18 21:35:16 I [0/0] [RTSP] [conn 192.168.1.10:60198] ERR: no one is publishing to path 'contre-allee'
rtsp-simple-server_1  | 2021/08/18 21:35:16 I [0/0] [RTSP] [conn 192.168.1.10:60198] closed
rtsp-simple-server_1  | 2021/08/18 21:35:16 I [0/0] [RTSP] [conn 192.168.1.10:60199] opened
rtsp-simple-server_1  | 2021/08/18 21:35:16 I [0/0] [RTSP] [session 224189300] opened by 192.168.1.10:60199
rtsp-simple-server_1  | 2021/08/18 21:35:16 I [0/0] [RTSP] [conn 192.168.1.10:60199] ERR: path must end with a slash (contre-allee)
rtsp-simple-server_1  | 2021/08/18 21:35:16 I [0/0] [RTSP] [conn 192.168.1.10:60199] closed
rtsp-simple-server_1  | 2021/08/18 21:35:16 I [0/0] [RTSP] [session 224189300] closed
rtsp-simple-server_1  | 2021/08/18 21:35:16 I [0/0] [RTSP] [conn 192.168.1.10:60200] opened
rtsp-simple-server_1  | 2021/08/18 21:35:16 I [0/0] [RTSP] [conn 192.168.1.10:60200] closed
```

When running the binairy, api is available : 
```
2021/08/18 22:28:55 I [0/0] [RTSP] UDP/RTP listener opened on :8000
2021/08/18 22:28:55 I [0/0] [RTSP] UDP/RTCP listener opened on :8001
2021/08/18 22:28:55 I [0/0] [RTSP] TCP listener opened on 0.0.0.0:8554
2021/08/18 22:28:55 I [0/0] [RTMP] listener opened on :1935
2021/08/18 22:28:55 I [0/0] [HLS] listener opened on :8888
2021/08/18 22:28:55 I [0/0] [API] listener opened on 0.0.0.0:9997
2021/08/18 22:28:55 D [0/0] [path contre-allee] [rtsp source] c->s SETUP rtsp://192.168.1.60:554/stream0/trackID=1 RTSP/1.0
```

Vlc is fine and i can curl api : 
```
{"items":{"contre-allee":{"confName":"contre-allee","conf":{"source":"rtsp://192.168.1.60:554/stream0?username=admin\u0026password=password","sourceProtocol":"automatic","sourceAnyPortEnable":false,"sourceFingerprint":"","sourceOnDemand":false,"sourceOnDemandStartTimeout":10000000000,"sourceOnDemandCloseAfter":10000000000,"sourceRedirect":"","disablePublisherOverride":false,"fallback":"","publishUser":"","publishPass":"","publishIPs":null,"readUser":"adm","readPass":"pass","readIPs":null,"runOnInit":"","runOnInitRestart":false,"runOnDemand":"","runOnDemandRestart":false,"runOnDemandStartTimeout":10000000000,"runOnDemandCloseAfter":10000000000,"runOnPublish":"","runOnPublishRestart":true,"runOnRead":"","runOnReadRestart":false},"source":{"type":"rtspSource"},"sourceReady":true,"readers":[]}}}
```
Disabling api isn't solving vlc issue, so I'm not sure how i can provide more details, just let me know.
Regards
