### ISSUE TITLE
Add support for webRTC streaming

### ISSUE THREAD

**Issue by GauravChoube** [aler9/rtsp-simple-server#566]
The only things missing in current project is webRTC which will provide less than 0.5s latency for live streaming.
As you may be aware of hls or ll-hls has at least 1-2s delay for live streaming.

Regards
Gaurav Choubey

**Comment by aler9** [comment]
Hello, the problem of WebRTC is that it requires video re-encoding from H264 to VP8 (or alternatively, the video track must already be in VP8). This can't be done without integrating a H264 decoder into the server, and this can cause legal problems, since the MPEG group requires a fee to distribute software that decodes H264.

It also requires audio re-encoding from AAC to Opus.

WebRTC theoretically also supports H264 (only the baseline profile), i did a lot of research into it during my job, but i never got it working.

Anyway, i'm leaving this feature request here, waiting for future developments.

**Comment by GauravChoube** [comment]
okay thanks for explanation.

**Comment by aarnaud** [comment]
Hi,

I think, It can work with some strict settings, like disable B-frame on h264 encoder 

I try rtsp-simple-server with https://github.com/deepch/RTSPtoWebRTC And it work fine. 

I did some test with OBS and FFmpeg as publisher. Of course with OBS we need to had a audio transcoder to switch to Opus codec. 

So I supposed it can work like this:
```
paths:
  all:
  original:
    runOnPublish: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH  -c:a opus -strict -2 -c:v copy -f rtsp rtsp://localhost:$RTSP_PORT/webrtc_$RTSP_PATH
    runOnPublishRestart: yes
```

An example with OBS:
![Screenshot from 2021-09-10 16-08-39](https://user-images.githubusercontent.com/4802105/132911732-88652f73-7963-4356-8613-f98bdd74ff34.png)

For exemple Wowza can convert RTMP to WebRTC: https://www.wowza.com/blog/converting-rtmp-to-webrtc-with-wowza-streaming-engine

Of course some browser can have limitations, I tried on Chrome/Chromium and Firefox, and Chrome Android and it work well.
