### ISSUE TITLE
Horrendous smearing

### ISSUE THREAD

**Issue by user897943** [aler9/rtsp-simple-server#589]
## Which version are you using?

"latest" - see image sha256 below

## Which operating system are you using?

OS

- [ X] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [X ] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

![image](https://user-images.githubusercontent.com/5891221/134771485-547c3f75-de14-4bf4-addf-dc4e44b1fe47.png)

I am seeing horrendous smearing on my CCTV, this is really really terrible.

## Describe how to replicate the issue

All cameras are set up like this:
![image](https://user-images.githubusercontent.com/5891221/134771529-90977854-3829-4aa0-ba19-6e74f8d56e41.png)

Log from container:
![image](https://user-images.githubusercontent.com/5891221/134771569-8a410a8d-39c8-4cb6-b4d9-a4c9762b51bd.png)

Stats from container:
![image](https://user-images.githubusercontent.com/5891221/134771645-12af2d29-e173-4c22-9950-2028aa2e30fc.png)

Docker image:
aler9/rtsp-simple-server@sha256:c4c1a5c8cada09f089c1161e9f3b853114e259557e9cab862c2d97ab2e46e089

Docker ports:
0.0.0.0:1935  1935/tcp:::1935  1935/tcp0.0.0.0:8554  8554/tcp:::8554  8554/tcp

Config file (rtsp URLs redacted):
```
api: yes
apiAddress: 127.0.0.1:9997
protocols: [tcp]
rtspPort: 8554
rtpPort: 8000
rtcpPort: 8001
readTimeout: 5s
writeTimeout: 5s
pprof: false
readBufferCount: 1024
readBufferSize: 8192

paths:
  cam1_ch1:
    source: "rtsp://1"
    sourceOnDemand: yes
    sourceProtocol: tcp
  cam2_ch1:
    source: "rtsp://2"
    sourceOnDemand: yes
    sourceProtocol: tcp
  cam3_ch1:
    source: "rtsp://3"
    sourceOnDemand: yes
    sourceProtocol: tcp
  cam4_ch1:
    source: "rtsp://4"
    sourceOnDemand: yes
    sourceProtocol: tcp
```

## Did you attach a network dump?

 no
