### ISSUE TITLE
ERR: non-existent parameter on reference in yaml

### ISSUE THREAD

**Issue by softko** [aler9/rtsp-simple-server#623]
## Which version are you using?

v0.17.4+

## Which operating system are you using?

OS

- [x] Linux

Architecture

- [x] amd64

## Describe the issue

In version 0.17.4 was added general feature "return error in case of non-existent parameters in the configuration file" but I think it should not check references (It should not return error if it is reference).
I have valid yaml which I was using until v0.17.3, but can't now:
```

commonstream: &common-stream-settings
  source: publisher
  sourceProtocol: tcp
  runOnPublish: >
    ffmpeg -re -i rtsps://READ_CAM_USER:READ_CAM_PASS@localhost:8555/$RTSP_PATH -c copy -f segment -segment_time FFMPEG_SEGMENT_SECONDS -reset_timestamps 1 -strftime 1 /stream/records/$RTSP_PATH/%Y-%m-%d_%H-%M-%S.mp4
  runOnPublishRestart: yes

.... general rtsp settings ...

paths:
  ~^(home1|home2)$:
    <<: *common-stream-settings
    readIPs: [127.0.0.1]
    publishIPs: [ALLOWED_FEED_IPS]
  ~^(hpcam|dellcam)$:
    <<: *common-stream-settings
    readUser: READ_CAM_USER
    readPass: READ_CAM_PASS
  ~^(pizcam|piz2cam)$:
    <<: *common-stream-settings
    readUser: READ_CAM_USER
    readPass: READ_CAM_PASS
    publishIPs: [ALLOWED_FEED_IPS]
....
```
Of course I can duplicate the setting and not use references, but that's the purpose of reference.

**Comment by aler9** [comment]
The server now checks for invalid keys in order to prevent user errors, that were frequent until now. This is the same behavior of docker-compose, Kubernetes, and a lot of other software.

There's no way to check whether a key is a reference or not.

In my opinion, you have two ways to solve the issue:

1. use a preprocessor that writes a plain YAML file from a template
2. move the reference inside paths:

```yml

.... general rtsp settings ...

paths:
  commonstream: &common-stream-settings
    source: publisher
    sourceProtocol: tcp
    runOnPublish: >
      ffmpeg -re -i rtsps://READ_CAM_USER:READ_CAM_PASS@localhost:8555/$RTSP_PATH -c copy -f segment -segment_time FFMPEG_SEGMENT_SECONDS -reset_timestamps 1 -strftime 1 /stream/records/$RTSP_PATH/%Y-%m-%d_%H-%M-%S.mp4
    runOnPublishRestart: yes
    readIPs: [127.0.0.1] # nobody allowed
    publishIPs: [127.0.0.1] # nobody allowed

  ~^(home1|home2)$:
    <<: *common-stream-settings
    readIPs: [127.0.0.1]
    publishIPs: [ALLOWED_FEED_IPS]
  ~^(hpcam|dellcam)$:
    <<: *common-stream-settings
    readUser: READ_CAM_USER
    readPass: READ_CAM_PASS
  ~^(pizcam|piz2cam)$:
    <<: *common-stream-settings
    readUser: READ_CAM_USER
    readPass: READ_CAM_PASS
    publishIPs: [ALLOWED_FEED_IPS]
```
