### ISSUE TITLE
Start RSTP server in windows(file source), and VLC could not connect and play

### ISSUE THREAD

**Issue by shaojun** [aler9/rtsp-simple-server#721]
### Discussed in https://github.com/aler9/rtsp-simple-server/discussions/720

<div type='discussions-op-text'>

<sup>Originally posted by **shaojun** December  7, 2021</sup>
Hi, thanks for the Repo.

I'm using Windows 10, downloaded the version `rtsp-simple-server_v0.17.10_windows_amd64`, the only changes I made in config is adding this section:

```
file1:
    runOnInit: ffmpeg -re -stream_loop -1 -i sample_720p.h264 -c copy -f rtsp rtsp://localhost:8554/mystream
    # runOnDemand: ffmpeg -hide_banner -loglevel error -avoid_negative_ts make_zero -fflags +genpts+nobuffer -flags low_delay -rtsp_transport tcp -use_wallclock_as_timestamps 1 -f rtsp -stimeout 5000000 -i rtsp://$USER:$PASSWORD@$CAMERA1:554/live0 -filter:a volume=10.0 -map 0:v -c:v:0 copy -map 0:a:0 -c:a:0 aac -map 0:a:0 -c:a:1 libopus -ac 1 -ar 16000 -b:a 8K -shortest -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnDemandRestart: yes
```

![image](https://user-images.githubusercontent.com/3241829/144956884-74eb50ce-99b7-4894-8ed4-984bcdc63e0c.png)

I've put 2 video files in the same folder of the App, and also tried put their file name in `runOnInit` line one by one:

![image](https://user-images.githubusercontent.com/3241829/144956980-80901d3f-634a-4115-a21d-6b15b5057a23.png)

I believe the server already started:

![image](https://user-images.githubusercontent.com/3241829/144957208-8cdd2a23-6474-4399-80b2-cb675263663d.png)

but the VLC in same machine always say `VLC could not connect to "localhost:8554".`:

![image](https://user-images.githubusercontent.com/3241829/144957068-fcff2fbc-aa28-4ad9-a37c-31c921f3a69c.png)

</div>
