### ISSUE TITLE
Record while the stream is being proxied

### ISSUE THREAD

**Issue by bobocancan** [aler9/rtsp-simple-server#752]
## Describe the feature

Description
It will be good if we can record the video to disk while the stream is being proxied.

**Comment by aler9** [comment]
Hello, a new parameter has been added to the configuration: `runOnReady` allows to launch commands when a stream is ready, whether it is being published by a client or being proxied. This allows to record the stream to disk even when the stream is being proxied:

```yml
paths:
  all:
  original:
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f segment -strftime 1 -segment_time 60 -segment_format mp4 saved_%Y-%m-%d_%H-%M-%S.mp4
    runOnReadyRestart: yes
```

This feature will be available in the next release.
