### ISSUE TITLE
Push streams to external rtsp-server

### ISSUE THREAD

**Issue by sanderux** [aler9/rtsp-simple-server#779]
I have the following setup

Computer 1
RTSP Camera publishing at localhost
rtsp-simple-server behind firewall

Server 1 public ip
rtsp-simple-server standard config relaying streams

Computer 2 behind firewall
Consuming the feed from server 1

Currently I use ffmpeg to consume and forward the rtsp stream to server 1. It would be great if I can use rtsp-simple-server to do this. I.E. have an actual pull push proxy function to consume the feed from the camera and publish it on the server.

**Comment by aler9** [comment]
Hello, you can do this by using `ffmpeg` inside  the `runOnReady` parameter of the instance installed on Computer 1:

```yml
paths:
  mycamera:
    source: rtsp://mycamera
    runOnReady: ffmpeg -re -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f rtsp rtsp://remote-server:8554/remote-path
    runOnReadyRestart: yes
```
