### ISSUE TITLE
 source ERR: no packets received recently (maybe there's a firewall/NAT in between)

### ISSUE THREAD

**Issue by q419456787** [aler9/rtsp-simple-server#87]
## Which version are you using?

rtsp-simple-server v0.9.14 

## Which operating system are you using?

Windows  

## Question
I add config  as follow
 paths:
     all:
        ......
     proxied:
        source: rtsp://192.168.1.19:554/stream0

I want to use rtsp proxy feature   but  it   response to me 
" source ERR: no packets received recently (maybe there's a firewall/NAT in between)"

 I can use   vlc to link rtsp://192.168.1.19:554/stream0     to see camera source   
 
how to resolve it  .

**Comment by aler9** [comment]
Hello, try using the tcp protocol
```yaml
paths:
  proxied:
    source: rtsp://192.168.1.19:554/stream0
    sourceProtocol: tcp
```
