### ISSUE TITLE
RTMP streamer gets kicked on when someone else streams on the same key

### ISSUE THREAD

**Issue by tompointexe** [aler9/rtsp-simple-server#911]
## Which version are you using?

v0.17.17

## Which operating system are you using?

- [x] Linux amd64 standard

## Describe the issue

When someone streams in RTMP, someone else can hijack the stream and kick the current person streaming

## Describe how to replicate the issue

1. start the server
2. publish with RTMP
3. read with anything you want
4. Publish on the same key with RTMP
5. the original streamer is kicked and the new one is 

## Did you attach the server logs?

nah, i dont think on this one

## Did you attach a network dump?

no

**Comment by aler9** [comment]
There's an option for that, i quote from the configuration file:

```yml
paths:
  all:
    # If the source is "publisher" and a client is publishing, do not allow another
    # client to disconnect the former and publish in its place.
    disablePublisherOverride: yes
```
