### ISSUE TITLE
Path-specific HLS settings

### ISSUE THREAD

**Issue by 0ip** [aler9/rtsp-simple-server#967]
Some devices like for example older low-end smartphones may not properly support LL-HLS and would be better off if provided with a classic HLS stream. However, this would require support for a path-specific `hlsVariant` setting (or pathi-specific HLS settings in general).

With that, I imagine a configuration could look like this:
```
paths:
  foo/classic:
    source: rtsp://bar/live/ch0
    hlsVariant: fmp4
  foo/fancy:
    source: rtsp://bar/live/ch0
    hlsVariant: lowLatency
```
