### ISSUE TITLE
Demux audio into separate stream

### ISSUE THREAD

**Issue by ismell** [aler9/rtsp-simple-server#99]
I would like to demux the audio into a separate stream. This way I can stream only the audio and ignore the video.

I have an RTSP video camera I'm using as a `baby cam`. I would like to add the URL as a custom radio station to my Sonos system.

Thanks!

**Comment by aler9** [comment]
Hello, this can be done wih ffmpeg:
```yml
paths:
  original:
    source: rtsp://original-url
    runOnInit: sh -c 'while true; do sleep 5; ffmpeg -i rtsp://localhost:8554/$RTSP_SERVER_PATH -map 0:a:0 -c copy -f rtsp rtsp://localhost:8554/audioonly; done'
```

Send the
